// /src/pages/Verification.jsx
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { useState } from 'react';
import Layout from '../components/Layout';
import DisclaimerBanner from '../components/DisclaimerBanner';
import { db } from '../firebase';
import { useAuth } from '../context/AuthContext';

const professions = ['Doctor','Nurse','Herbalist','Nutritionist','Pharmacist','Naturopath','Ayurveda practitioner','Wellness educator','Other'];

export default function Verification() {
  const { user } = useAuth();
  const [form, setForm] = useState({ fullName: '', profession: 'Herbalist', licenseNumber: '', location: '', credentialUrl: '', credentialDescription: '', yearsExperience: '', bio: '', agree: false });
  const [message, setMessage] = useState('');
  async function submit(e) { e.preventDefault(); if (!user) return setMessage('Please sign in first.'); if (!form.agree) return setMessage('Please accept the agreement.'); await addDoc(collection(db,'verificationRequests'), { ...form, uid: user.uid, status: 'pending', createdAt: serverTimestamp(), reviewedAt: null, reviewedBy: '' }); setMessage('Your verification request was submitted.'); }
  return <Layout><DisclaimerBanner /><div className="glass-card rounded-3xl p-6 shadow-soft"><h1 className="hero-title mb-2 text-4xl font-bold text-forest">Expert Verification</h1><p className="mb-6 text-sm text-stone-600">Apply to have your credentials reviewed by HerbaCircle admins.</p>{message && <p className="mb-4 rounded-xl bg-mint p-3 text-sm font-semibold text-forest">{message}</p>}<form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><input className="rounded-2xl border border-sage/20 px-4 py-3" placeholder="Full legal name" value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})} required/><select className="rounded-2xl border border-sage/20 px-4 py-3" value={form.profession} onChange={(e)=>setForm({...form,profession:e.target.value})}>{professions.map(p=><option key={p}>{p}</option>)}</select><input className="rounded-2xl border border-sage/20 px-4 py-3" placeholder="License number if applicable" value={form.licenseNumber} onChange={(e)=>setForm({...form,licenseNumber:e.target.value})}/><input className="rounded-2xl border border-sage/20 px-4 py-3" placeholder="Country/state" value={form.location} onChange={(e)=>setForm({...form,location:e.target.value})}/><input className="rounded-2xl border border-sage/20 px-4 py-3 md:col-span-2" placeholder="Credential URL" value={form.credentialUrl} onChange={(e)=>setForm({...form,credentialUrl:e.target.value})}/><input className="rounded-2xl border border-sage/20 px-4 py-3" placeholder="Years of experience" type="number" value={form.yearsExperience} onChange={(e)=>setForm({...form,yearsExperience:e.target.value})}/><input className="rounded-2xl border border-sage/20 px-4 py-3" placeholder="Credential description" value={form.credentialDescription} onChange={(e)=>setForm({...form,credentialDescription:e.target.value})}/><textarea className="min-h-32 rounded-2xl border border-sage/20 px-4 py-3 md:col-span-2" placeholder="Short bio" value={form.bio} onChange={(e)=>setForm({...form,bio:e.target.value})}/><label className="flex gap-3 rounded-2xl bg-cream p-4 text-sm md:col-span-2"><input type="checkbox" checked={form.agree} onChange={(e)=>setForm({...form,agree:e.target.checked})}/> I understand that HerbaCircle may review my credentials and that my posts must not replace medical advice.</label><button className="rounded-2xl bg-forest px-6 py-4 font-bold text-white md:col-span-2">Submit Verification Request</button></form></div></Layout>;
}
